### ISSUE TITLE
[Bug]: Bach UI / API taking excessive resources and bringing GRQ down

### ISSUE THREAD

**Issue by riverma** [nasa/opera-sds-bach-api#28]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

When a granule report is requested from Bach UI that involves a time range that has a significant amount of data in Elasticsearch, CPU use skyrockets and this brings the underlying GRQ machine to a standstill. This is a critical issue since GRQ is a core machine for HySDS and this bug can affect operation user interfaces. This is likely caused by OPERA-specific code, not HySDS core.

### What did you expect?

We expect all reports on Bach UI to return in an efficient manner (within seconds), and to not cause the underlying GRQ machine to come to a standstill due to CPU spikes.

### Reproducible steps

```bash
1. Have ~10k granule metadata available in Elasticsearch
2. Open Bach UI
3. Click Generate Report
```

### Environment

```bash
- OPERA GRQ machine
- HySDS v(?)
- OPERA SDS v1-RC6
```

**Comment by hookhua** [comment]
It was observed that when the `bach_ui` was used to initiate a "_retrieval time summary_" report, it resulted on the `bach-api` running on GRQ spinning up `gunicorn` processes up to 99% CPU and monotonically increasing memory usage. The `bach-api's gunicorn` process eventually uses up all physical memory and brings down GRQ.

One action item is debug the accountability report code[ noted above](https://github.com/nasa/opera-sds-bach-api/issues/28#issuecomment-1363419101). Any type of accountability report should not get stuck into an infinite loop. It appears to be a bug.

A second action item is to move `bach-api `and `bach_ui` out of GRQ and Mozart, respectively. Either move it to Factotum or to another resource. This way, data accountability reporting would not impact critical path functionality of PCM.

**Comment by riverma** [comment]
Per @hookhua's suggestion, another ticket is available here: https://github.com/nasa/opera-sds-pcm/issues/339
