### ISSUE TITLE
[Bug]: Retrieval Time reports showing zero retrieval time

### ISSUE THREAD

**Issue by sjlewis-jpl** [nasa/opera-sds-bach-api#39]
### Checked for duplicates

No - I haven't checked

### Describe the bug

When I did looked at the retrieval time reports generated by Ops during May, a number of inputs showed a retrieval time of 0 seconds.  This was observed in the daily retrieval time reports from 5/12 - 5/16.  After discussion on the PCM slack channel, there seems to be information loss when generating the reports.

### What did you expect?

I expect the reports to have accurate information - time stamps should reflect the actual time something happened in our system.  Any timestamp that isn't known is either 

1. an error (either in our code, or in how we're storing the information)
2. or hasn't happened yet (when the report is generated)

### Reproducible steps

```bash
Presumably regenerating the production time and retrieval time reports for the days May 12 - 16 would replicate the problem.  I didn't generate the reports, I just have been looking at the resulting CSV files.  The CSV files can be found on GDrive (https://drive.google.com/drive/folders/1xJbzyg5gsE9xKMNcB2bb38X696N5kbvj?usp=share_link)
```

### Environment

```bash
Whatever is running in FWD Operations for DSWx-HLS on May 16 (when the reports in question were generated).
```

**Comment by hhlee445** [comment]
We need to expand report time range in Bach and clean up columns in reports as
- remove OPERA Product Short Name column on RETRIEVAL TIME SUMMARY report.
- remove OPERA Product Short Name and OPERA Product Name columns on RETRIEVAL TIME DETAIL report
